name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true

jobs:
  release:
    runs-on: [macos-latest]
    services:
      docker:
        image: docker:dind
        options --privileged --shm-size=2g
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
    steps:
    - uses: actions/checkout@v1

    - name: Release
      run: ./script/release ${{ github.event.inputs.version }}  ${{ secrets.GITHUB_TOKEN }}
